name: rich-text
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.8
  - cudatoolkit=11.7.0
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1
  - numpy=1.19.2
  - pip:
    - diffusers==0.12.1
    - seaborn==0.12.2
    - transformers==4.26.0
    - imageio==2.25.0
    - gradio==3.24.1
    - scikit-learn==0.24.1