name: rich-text
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.8
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - diffusers==0.12.1
    - seaborn==0.12.2
    - transformers==4.25.1
    - imageio==2.9.0
    - gradio==3.24.1